print("Welcome to the tip calculator")
total_bill = float(input("What was the total bill?\n>>"))
tip = int(input("How much tip would you like to give?\n>>"))
people = int(input("How many people to split the bill?\n>>"))
amount_per_person = round(((total_bill * (tip/100) + total_bill) / people), 2)
print(f"Each person should pay: {amount_per_person}")